services:
  # 1. Fusion Orchestrator (Backend API)
  - type: web
    name: mci-backend-fusion
    env: docker
    repo: https://github.com/AbhayRao38/Model_Fusion.git
    plan: free
    envVars:
      - key: FACE_HOST
        value: https://darkxcrafter-mci-model-face.hf.space
      - key: EYE_HOST
        value: https://darkxcrafter-mci-model-eye.hf.space
      - key: SPEECH_HOST
        value: https://darkxcrafter-mci-model-speech.hf.space
      - key: MRI_HOST
        value: https://darkxcrafter-mci-model-mri.hf.space

  # 2. Static HTML/JS Frontend
  - type: static
    name: mci-frontend
    repo: https://github.com/AbhayRao38/Model_Fusion.git
    buildCommand: ""
    publishPath: frontend
