services:
  # 1. Fusion Orchestrator (Backend API)
  - type: web
    name: mci-backend-fusion
    env: python
    repo: https://github.com/AbhayRao38/Model_Fusion.git
    buildCommand: "pip install -r requirements.txt && pip install gunicorn"
    startCommand: "gunicorn -w 1 -b 0.0.0.0:$PORT main:app"
    plan: free
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.11
      - key: FACE_HOST
        value: https://darkxcrafter-mci-model-face.hf.space
      - key: EYE_HOST
        value: https://darkxcrafter-mci-model-eye.hf.space
      - key: SPEECH_HOST
        value: https://darkxcrafter-mci-model-speech.hf.space
      - key: MRI_HOST
        value: https://darkxcrafter-mci-model-mri.hf.space

  # 2. Static HTML/JS Frontend
  - type: web
    name: mci-frontend
    runtime: static
    rootDir: frontend
    repo: https://github.com/AbhayRao38/Model_Fusion.git
    buildCommand: ""
    staticPublishPath: .
